apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | nindent 6 }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector: {{ include "common.labels" . | nindent 6 }}